services:
    db:
      image: mdillon/postgis:9.4
      container_name: gps_collector_db
      environment:
        POSTGRES_DB: gps_collector
        POSTGRES_PASSWD: mudeiasenha
        POSTGRES_USER: postgres
      ports:
        - "5432:5432"
